server:
  port: 3000

datasource:
  url: jdbc:h2:mem:testDB
  driverClassName: org.h2.Driver
  username: sa
  password:

spring:
  h2:
    console:
      enabled: true  #will be present at /h2-console

logging:
  level:
    root: info
